// Centralized UI strings for Homebrew Haven
// Import from this file instead of hardcoding strings

export const APP = {
  appName: "Homebrew Haven",
  tagline: "Craft Your Perfect Brew",
  version: "1.0.0",
} as const

export const AUTH = {
  login: "Sign In",
  signup: "Sign Up",
  logout: "Sign Out",
  welcomeBack: "Welcome back!",
  createAccount: "Create an account",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm Password",
  orContinueWith: "Or continue with",
  alreadyHaveAccount: "Already have an account?",
  dontHaveAccount: "Don't have an account?",
} as const

export const BREW = {
  upcomingActions: "Upcoming Actions",
  recentReadings: "Recent Readings",
  startNewBrew: "Start a New Brew",
  brewDay: "Brew day",
  fermenting: "Fermenting",
  conditioning: "Conditioning",
  packaging: "Packaging",
  batchShelf: "Batch Shelf",
  currentBatch: "Current Batch",
  completedBatches: "Completed Batches",
  fermentationLog: "Fermentation Log",
  targetGravity: "Target Gravity",
  originalGravity: "Original Gravity",
  finalGravity: "Final Gravity",
  brewingHistory: "Brewing History",
} as const

export const ACTIONS = {
  save: "Save",
  delete: "Delete",
  edit: "Edit",
  share: "Share",
  cancel: "Cancel",
  confirm: "Confirm",
  view: "View",
  follow: "Follow",
  unfollow: "Unfollow",
  add: "Add",
  remove: "Remove",
  search: "Search",
  filter: "Filter",
  sort: "Sort",
  close: "Close",
  back: "Back",
  next: "Next",
  submit: "Submit",
  loading: "Loading...",
  retry: "Retry",
} as const

export const RECIPE = {
  brewThis: "Brew this",
  shareRecipe: "Share Recipe",
  featuredRecipes: "Featured Recipes",
  curated: "Curated Collection",
  myRecipes: "My Recipes",
  savedRecipes: "Saved Recipes",
  recipeDetails: "Recipe Details",
  author: "Author",
  style: "Style",
  abv: "ABV",
  ibu: "IBU",
  srm: "SRM",
  rating: "Rating",
  reviews: "Reviews",
} as const

export const FORMS = {
  name: "Name",
  description: "Description",
  requiredField: "This field is required",
  optional: "Optional",
  selectDate: "Select date",
  selectTime: "Select time",
  notes: "Notes",
  tags: "Tags",
  category: "Category",
  ingredients: "Ingredients",
  instructions: "Instructions",
  batchSize: "Batch Size",
  brewTime: "Brew Time",
  difficulty: "Difficulty",
} as const

export const copy = {
  profile: {
    editProfile: "Edit Profile",
    follow: "Follow",
    unfollow: "Unfollow",
    batches: "Batches",
    recipes: "Recipes",
    followers: "Followers",
    following: "Following",
    noBioYet: "No bio yet.",
    brewLogs: "Brew logs",
    myRecipes: "My recipes",
    savedRecipes: "Saved",
    batchShelf: "Batch shelf",
    yeastBank: "Yeast bank",
    finished: "Finished",
    followUnfollow: (action: "follow" | "unfollow") => action === "follow" ? "Follow" : "Unfollow",
    followersCount: (n: number) => `${n} Follower${n !== 1 ? "s" : ""}`,
    followingCount: (n: number) => `${n} Following`,
    noBatchesYet: "No batches yet.",
    noRecipesYet: "No recipes yet.",
    noBrewLogsYet: "No brew logs yet.",
    noYeastStrainsYet: "No yeast strains saved yet.",
    noFollowersYet: "No followers yet.",
    notFollowingAnyone: "Not following anyone yet.",
    followBack: "Follow back",
    viewAll: "View all",
    editProfileTitle: "Edit Profile",
    editProfileDescription: "Update your profile information.",
    displayName: "Display Name",
    location: "Location",
    bio: "Bio",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    signOut: "Sign Out",
    appearance: "Appearance",
    deleteStrain: "Delete strain",
    addYeastStrain: "Add Yeast Strain",
    addStrain: "Add Strain",
    yeastName: "Name",
    strainCode: "Strain Code",
    notes: "Notes",
    yeastNamePlaceholder: "e.g. WLP001 California Ale",
    strainCodePlaceholder: "Optional code",
    notesPlaceholder: "Attenuation, temp range, etc.",
    bioPlaceholder: "Tell us about your brewing style...",
    displayNamePlaceholder: "Brewer Name",
    locationPlaceholder: "City, Country",
    noCoverPhoto: "No cover photo",
    uploadCoverPhoto: "Upload cover photo",
    loadingProfile: "Loading profile...",
    awards: "Awards & Badges",
    connections: "Connections",
    accountSettings: "Account Settings",
    signedInAs: "Signed in as",
    noBadgesYet: "No badges earned yet.",
    noFinishedBatches: "No finished batches yet.",
    source: "Source",
    generation: "Generation",
    storageDate: "Storage date",
    viability: "Viability",
    batchName: "Batch",
    batchType: "Type",
    srm: "SRM",
    dateCompleted: "Completed",
    starRating: "Rating",
    posts: "Posts",
    postTitle: "Title",
    postContent: "Content",
    postDate: "Date",
    noContentYet: "Nothing here yet.",
    manageAccount: "Manage Account",
    labStats: "Lab Stats",
    totalBatches: "Total batches",
    completedBatches: "Completed",
    avgBrewDays: "Avg brew days",
    favouriteStyle: "Favourite style",
  },
  common: {
    loading: "Loading...",
    error: "Something went wrong.",
    noResults: "No results found.",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    share: "Share",
    close: "Close",
    view: "View",
  },
  community: {
    brewLogs: "Brew Logs",
    troubleshooting: "Troubleshooting",
    tastings: "Tastings",
    challenges: "Challenges",
    joinDiscussion: "Join the Discussion",
    noPosts: "No posts yet in this category.",
    sortLatest: "Latest",
    sortMostLiked: "Most Liked",
    sortMostCommented: "Most Commented",
    following: "Following",
    all: "All",
    comments: "Comments",
  },
  settings: {
    title: "Settings",
    subtitle: "Manage your account and preferences",
    back: "Back",
    sections: {
      account: "Account",
      accountDesc: "Update your profile photo, name, and bio",
      security: "Security",
      securityDesc: "Manage email, password, and connected accounts",
      notifications: "Notifications",
      notificationsDesc: "Choose how you receive updates",
      preferences: "Preferences",
      preferencesDesc: "Units and display preferences",
      privacy: "Privacy",
      privacyDesc: "Control who sees your content",
      danger: "Danger Zone",
      dangerDesc: "Irreversible account actions",
    },
    account: {
      avatar: "Avatar",
      coverPhoto: "Cover Photo",
      uploadCover: "Upload",
      displayName: "Display Name",
      username: "Username",
      location: "Location",
      bio: "Bio",
      brewingSince: "Brewing Since",
      favouriteStyles: "Favourite Styles",
      saveProfile: "Save Profile",
    },
    security: {
      changeEmail: "Change Email",
      changePassword: "Change Password",
      connectedAccounts: "Connected Accounts",
      activeSessions: "Active Sessions",
      twoFactor: "Two-Factor Authentication",
      twoFactorDesc: "Add an extra layer of security",
      comingSoon: "Coming soon",
      currentSession: "Current",
      current: "Current session",
      revoke: "Revoke",
      active: "Active",
      connected: "Connected",
      newEmail: "New Email",
      currentPassword: "Current Password",
      newPasswordLabel: "New Password",
      updatePassword: "Update Password",
    },
    notifications: {
      type: "Notification Type",
      inApp: "In-app",
      email: "Email",
    },
    preferences: {
      tempUnit: "Temperature Unit",
      tempUnitDesc: "Default unit for temperature readings",
      gravityUnit: "Gravity Unit",
      gravityUnitDesc: "Default unit for gravity readings",
      volumeUnit: "Volume Unit",
      volumeUnitDesc: "Default unit for batch volume",
      theme: "Theme",
      themeDesc: "Light, dark, or follow system",
    },
    privacy: {
      profileVisibility: "Profile Visibility",
      profileVisibilityDesc: "Who can see your full profile",
      batchVisibility: "Batch Shelf Visibility",
      batchVisibilityDesc: "Who can see your finished batches",
      yeastVisibility: "Yeast Bank Visibility",
      yeastVisibilityDesc: "Who can see your yeast bank",
      public: "Public",
      private: "Private",
      everyone: "Everyone",
      followersOnly: "Followers Only",
      onlyMe: "Only Me",
    },
    dangerZone: {
      exportData: "Export Your Data",
      exportDataDesc: "Download a copy of all your data",
      exportDataBtn: "Export",
      deleteAccount: "Delete Account",
      deleteAccountDesc: "Permanently remove your account and all data",
      deleteAccountBtn: "Delete Account",
      deleteAccountConfirmTitle: "Delete Account?",
      deleteAccountConfirmDesc: "This action is irreversible. All your batches, recipes, and data will be permanently deleted.",
      typeEmailToConfirm: "Type your email address to confirm:",
      deleteAccountFinalBtn: "Yes, Delete My Account",
    },
  },
} as const

export type Copy = typeof copy